FROM python:3.9-slim

RUN pip install --upgrade pip

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

RUN pip install .

EXPOSE 8000
CMD ["uvicorn", "fastapi_xcc.app:app", "--host", "0.0.0.0", "--port", "8000"]